import { ProviderSpec } from "./generic-openai.provider";

// 内置供应商清单（多 provider / 多模型）。用户在设置里填各自 apiKey/apiUrl。
// 全部走 OpenAI 兼容协议；Anthropic 走其 OpenAI 兼容端点，cache_control 触发 Claude 缓存命中。
export const PROVIDER_SPECS: ProviderSpec[] = [
  {
    id: "openai",
    name: "OpenAI",
    defaultApiUrl: "https://api.openai.com/v1",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    description: "GPT 系列（文本 + DALL·E 生图）",
    protocols: ["openai", "openai-response"],
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini", "o4-mini", "dall-e-3", "gpt-image-1"],
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    defaultApiUrl: "https://api.anthropic.com/v1",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    description: "Claude 系列（OpenAI 兼容端点，支持提示缓存命中）",
    protocols: ["anthropic", "openai"],
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-3-7-sonnet", "claude-3-5-haiku"],
  },
  {
    id: "google",
    name: "Google (Gemini)",
    defaultApiUrl: "https://generativelanguage.googleapis.com",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    description: "Gemini 系列（谷歌原生协议）",
    protocols: ["gemini"],
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    defaultApiUrl: "https://api.deepseek.com/v1",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    description: "深度求索",
    models: ["deepseek-chat", "deepseek-reasoner"],
  },
  {
    id: "qwen",
    name: "通义千问 (DashScope)",
    defaultApiUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKeyUrl: "https://bailian.console.aliyun.com/",
    description: "阿里云百炼（文本 + 通义万相生图）",
    models: ["qwen-plus", "qwen-max", "qwen-turbo", "qwen-vl-plus", "wanx2.1-t2i-turbo"],
  },
  {
    id: "moonshot",
    name: "月之暗面 (Kimi)",
    defaultApiUrl: "https://api.moonshot.cn/v1",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    description: "Kimi",
    models: ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k", "kimi-k2-0905-preview"],
  },
  {
    id: "zhipu",
    name: "智谱 (GLM)",
    defaultApiUrl: "https://open.bigmodel.cn/api/paas/v4",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    description: "GLM 系列",
    models: ["glm-4.6", "glm-4-plus", "glm-4-flash"],
  },
  {
    id: "volcengine",
    name: "火山方舟 (豆包)",
    defaultApiUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKeyUrl: "https://console.volcengine.com/ark",
    description: "豆包 Doubao",
    models: ["doubao-pro-32k", "doubao-pro-128k", "doubao-1-5-pro-32k"],
  },
  {
    id: "siliconflow",
    name: "硅基流动",
    defaultApiUrl: "https://api.siliconflow.cn/v1",
    apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
    description: "聚合多家开源模型",
    models: ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct"],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    defaultApiUrl: "https://openrouter.ai/api/v1",
    apiKeyUrl: "https://openrouter.ai/keys",
    description: "全球模型聚合",
    models: ["anthropic/claude-sonnet-4.5", "openai/gpt-4o", "google/gemini-2.5-pro"],
  },
  {
    id: "custom",
    name: "自定义",
    defaultApiUrl: "",
    description: "任意 OpenAI 兼容端点：填 baseURL + 模型名即可（文本/生图通用）",
    protocols: ["openai", "openai-response", "anthropic"],
    models: [],
  },
];
